### ISSUE TITLE
Disable kamal-proxy version vX.Y is too old ERROR

### ISSUE THREAD

**Issue by aktech** [basecamp/kamal-proxy#50]
It's been an hour since the release of new `kamal-proxy` and we have started seeing errors on deployment.

```yml
Releasing the deploy lock...
  Finished all in 58.8 seconds
  ERROR (RuntimeError): Exception while executing on host X.X.X.X: kamal-proxy version v0.8.0 is too old, please reboot to update to at least v0.8.1
Error: Process completed with exit code 1.
```

Deployments should not fail for this reason. :)

Perhaps there is a way to disable this?

**Comment by kevinmcconnell** [comment]
Currently each Kamal release is pinned to a specific Kamal Proxy version. So if you upgrade Kamal to a new version that is pinned to a different proxy version, then you also need to update the proxy along with it. (The message you see here comes from Kamal, not Kamal Proxy; that's where we enforce the restriction).

You can continue to use Kamal 2.2.0 instead of 2.2.1 if you're not ready to do the `kamal proxy reboot` step.

We are planning to relax this restriction somewhat (perhaps allowing minor or patch version differences) but keeping both sides closely in step has been valuable while we've been building out the features in both.

I'm closing this since it's really a Kamal question rather than a Kamal Proxy one. Would suggest opening a discussion on the Kamal repo if you'd like to discuss some alternatives, though.
